language: python
addons:
    artifacts:
        debug: true
        paths:
        - dist/
python:
    - '2.7'
install:
    - pip install -r requirements.txt
    - pyinstaller nginx_installer.spec
script: true
